input {
  # Menerima log JSON murni lewat jalur TCP di port 5000
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # (Opsional) Di sini Anda bisa memanipulasi data sebelum masuk database
}

output {
  # Buang lognya ke Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "wms-logs-%{+YYYY.MM.dd}" # Nama tabel di Elasticsearch, dipisah per hari
  }
  
# Tetap print ke terminal Docker Logstash untuk debugging
stdout { codec => rubydebug } 
}