// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/models"
	mock "github.com/stretchr/testify/mock"
)

// AdjustmentRepository is an autogenerated mock type for the AdjustmentRepository type
type AdjustmentRepository struct {
	mock.Mock
}

// ExecuteAdjustment provides a mock function with given fields: adjustment, newStock
func (_m *AdjustmentRepository) ExecuteAdjustment(adjustment *models.StockAdjustment, newStock int) error {
	ret := _m.Called(adjustment, newStock)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteAdjustment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.StockAdjustment, int) error); ok {
		r0 = rf(adjustment, newStock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteMassAdjustment provides a mock function with given fields: adjustments, stockUpdates
func (_m *AdjustmentRepository) ExecuteMassAdjustment(adjustments []models.StockAdjustment, stockUpdates map[uint]int) error {
	ret := _m.Called(adjustments, stockUpdates)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteMassAdjustment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.StockAdjustment, map[uint]int) error); ok {
		r0 = rf(adjustments, stockUpdates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdjustmentRepository creates a new instance of AdjustmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdjustmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdjustmentRepository {
	mock := &AdjustmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
