// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/models"
	mock "github.com/stretchr/testify/mock"
)

// BatchRepository is an autogenerated mock type for the BatchRepository type
type BatchRepository struct {
	mock.Mock
}

// FindByProductID provides a mock function with given fields: productID
func (_m *BatchRepository) FindByProductID(productID uint) ([]models.ProductBatch, error) {
	ret := _m.Called(productID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProductID")
	}

	var r0 []models.ProductBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.ProductBatch, error)); ok {
		return rf(productID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.ProductBatch); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ProductBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBatch provides a mock function with given fields: batch
func (_m *BatchRepository) UpdateBatch(batch *models.ProductBatch) error {
	ret := _m.Called(batch)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ProductBatch) error); ok {
		r0 = rf(batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBatchRepository creates a new instance of BatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchRepository {
	mock := &BatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
