// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/models"
	mock "github.com/stretchr/testify/mock"
)

// LocationRepository is an autogenerated mock type for the LocationRepository type
type LocationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: location
func (_m *LocationRepository) Create(location *models.Location) error {
	ret := _m.Called(location)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Location) error); ok {
		r0 = rf(location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *LocationRepository) FindAll() ([]models.Location, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Location
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Location, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Location); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Location)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCode provides a mock function with given fields: code
func (_m *LocationRepository) FindByCode(code string) (*models.Location, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Location, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Location); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLocationRepository creates a new instance of LocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocationRepository {
	mock := &LocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
