// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/models"
	mock "github.com/stretchr/testify/mock"
)

// PartnerRepository is an autogenerated mock type for the PartnerRepository type
type PartnerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: partner
func (_m *PartnerRepository) Create(partner *models.Partner) error {
	ret := _m.Called(partner)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Partner) error); ok {
		r0 = rf(partner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *PartnerRepository) FindAll() ([]models.Partner, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Partner
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Partner, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Partner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Partner)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *PartnerRepository) FindByID(id uint) (*models.Partner, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Partner
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Partner, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Partner); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Partner)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPartnerRepository creates a new instance of PartnerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartnerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartnerRepository {
	mock := &PartnerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
