// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/models"
	repositories "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/repositories"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// AnalyzeProductMovement provides a mock function with given fields: startDate, endDate
func (_m *TransactionRepository) AnalyzeProductMovement(startDate time.Time, endDate time.Time) ([]repositories.ProductMovementResult, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeProductMovement")
	}

	var r0 []repositories.ProductMovementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]repositories.ProductMovementResult, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []repositories.ProductMovementResult); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.ProductMovementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApproveAndUpdateStock provides a mock function with given fields: tx, stockUpdates
func (_m *TransactionRepository) ApproveAndUpdateStock(tx *models.Transaction, stockUpdates map[uint]int) error {
	ret := _m.Called(tx, stockUpdates)

	if len(ret) == 0 {
		panic("no return value specified for ApproveAndUpdateStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction, map[uint]int) error); ok {
		r0 = rf(tx, stockUpdates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteMultiWarehouseMutation provides a mock function with given fields: tx, stockMutations
func (_m *TransactionRepository) ExecuteMultiWarehouseMutation(tx *models.Transaction, stockMutations map[string]int) error {
	ret := _m.Called(tx, stockMutations)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteMultiWarehouseMutation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction, map[string]int) error); ok {
		r0 = rf(tx, stockMutations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteTransaction provides a mock function with given fields: txData, stockUpdates
func (_m *TransactionRepository) ExecuteTransaction(txData *models.Transaction, stockUpdates map[uint]int) error {
	ret := _m.Called(txData, stockUpdates)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction, map[uint]int) error); ok {
		r0 = rf(txData, stockUpdates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *TransactionRepository) FindByID(id uint) (*models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOutboundItemsByDate provides a mock function with given fields: startDate, endDate
func (_m *TransactionRepository) FindOutboundItemsByDate(startDate time.Time, endDate time.Time) ([]models.TransactionItem, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for FindOutboundItemsByDate")
	}

	var r0 []models.TransactionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]models.TransactionItem, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []models.TransactionItem); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TransactionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTransactionsByDateRange provides a mock function with given fields: startDate, endDate
func (_m *TransactionRepository) FindTransactionsByDateRange(startDate time.Time, endDate time.Time) ([]models.Transaction, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for FindTransactionsByDateRange")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]models.Transaction, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []models.Transaction); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTransactionsPaginatedByDate provides a mock function with given fields: startDate, endDate, limit, offset
func (_m *TransactionRepository) FindTransactionsPaginatedByDate(startDate time.Time, endDate time.Time, limit int, offset int) ([]models.Transaction, error) {
	ret := _m.Called(startDate, endDate, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindTransactionsPaginatedByDate")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, int, int) ([]models.Transaction, error)); ok {
		return rf(startDate, endDate, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, int, int) []models.Transaction); ok {
		r0 = rf(startDate, endDate, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time, int, int) error); ok {
		r1 = rf(startDate, endDate, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
