// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/models"
	mock "github.com/stretchr/testify/mock"
)

// WarehouseRepository is an autogenerated mock type for the WarehouseRepository type
type WarehouseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: warehouse
func (_m *WarehouseRepository) Create(warehouse *models.Warehouse) error {
	ret := _m.Called(warehouse)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Warehouse) error); ok {
		r0 = rf(warehouse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *WarehouseRepository) FindAll() ([]models.Warehouse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Warehouse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Warehouse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *WarehouseRepository) FindByID(id uint) (*models.Warehouse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Warehouse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Warehouse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWarehouseRepository creates a new instance of WarehouseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseRepository {
	mock := &WarehouseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
