// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/affandisy/go-one-week-one-project/week-02-warehouse-system/models"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// WarehouseStockRepository is an autogenerated mock type for the WarehouseStockRepository type
type WarehouseStockRepository struct {
	mock.Mock
}

// GetStock provides a mock function with given fields: warehouseID, productID
func (_m *WarehouseStockRepository) GetStock(warehouseID uint, productID uint) (*models.WarehouseStock, error) {
	ret := _m.Called(warehouseID, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 *models.WarehouseStock
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*models.WarehouseStock, error)); ok {
		return rf(warehouseID, productID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *models.WarehouseStock); ok {
		r0 = rf(warehouseID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WarehouseStock)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(warehouseID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertStock provides a mock function with given fields: warehouseID, productID, qty, tx
func (_m *WarehouseStockRepository) UpsertStock(warehouseID uint, productID uint, qty int, tx *gorm.DB) error {
	ret := _m.Called(warehouseID, productID, qty, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpsertStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, int, *gorm.DB) error); ok {
		r0 = rf(warehouseID, productID, qty, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWarehouseStockRepository creates a new instance of WarehouseStockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseStockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseStockRepository {
	mock := &WarehouseStockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
